name: continuous-integration

on:
  push:
    branches:
      - master
      - versi-support
  pull_request:
    branches:
      - master
      - versi-support
    paths-ignore:
      - '**/*.md'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'FILE_TEMPLATE'

env:
  DOCKERFILE: "Dockerfile"
  IMAGE_NAME: sergejparity/calamar

jobs:
  build-publish-docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up tag
        run: echo "IMAGE_TAG=${GITHUB_REF_NAME}-${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build/Push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ${{ env.DOCKERFILE }}
          build-args: |
            VCS_REF="${{ github.sha }}"
            build-arg BUILD_DATE="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"
            build-arg VERSION="$IMAGE_TAG"
            build-arg PROJECT_NAME="$GITHUB_REPOSITORY"
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.IMAGE_NAME }}:latest
